packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  "@types/node": 22.9.0
  "@vercel/functions": 1.5.0
  chalk: 5.3.0
  hono: 4.6.10
  next: 15.0.3
  next-axiom: 1.5.1
  postcss: ^8.4.49
  react: 19.0.0-rc.1
  react-dom: 19.0.0-rc.1
  server-only: 0.0.1
  tailwindcss: ^3.4.15
  "@types/react": npm:types-react@19.0.0-rc.1
  "@types/react-dom": npm:types-react@19.0.0-rc.1
  typescript: 5.6.3
  zod: 3.23.8
catalogs:
  react18:
    "@types/react": 18.3.12
    "@types/react-dom": 18.3.1
    react: 18.3.1
    react-dom: 18.3.1
