packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  "@types/node": 22.10.1
  "@types/react-dom": npm:types-react@19.0.0-rc.1
  "@types/react": npm:types-react@19.0.0-rc.1
  "@vercel/functions": 1.5.1
  chalk: 5.3.0
  hono: 4.6.12
  next-axiom: 1.6.0
  next: 15.0.3
  pino: 9.5.0
  postcss: ^8.4.49
  react-dom: 19.0.0-rc-7670501b-20241124
  react: 19.0.0-rc-7670501b-20241124
  server-only: 0.0.1
  tailwindcss: ^3.4.15
  typescript: 5.7.2
  vitest: ^2.1.6
  zod: 3.23.8
catalogs:
  react18:
    "@types/react": 18.3.1
    "@types/react-dom": 18.3.1
    react: 18.3.1
    react-dom: 18.3.1
