packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@types/node': 22.9.0
  '@types/react': ^18.3.12
  '@types/react-dom': ^18.3.1
  next: 15.0.3
  postcss: ^8.4.47
  react: 19.0.0-rc-66855b96-20241106
  react-dom: 19.0.0-rc-66855b96-20241106
  tailwindcss: ^3.4.14
  typescript: 5.6.3
  zod: 3.23.8
