packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  "@tanstack/react-router": 1.97.1
  "@tanstack/router-devtools": 1.97.1
  "@tanstack/router-plugin": 1.97.1
  "@types/node": 22.10.7
  "@vercel/functions": 1.5.2
  autoprefixer: 10.4.20
  hono: 4.6.16
  next: 15.1.6
  next-axiom: 1.9.1
  pino: 9.6.0
  postcss: ^8.5.1
  server-only: 0.0.1
  tailwindcss: 3.4.17
  typescript: 5.7.3
  vitest: ^3.0.1
  zod: 3.24.1
catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
