packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  "@types/node": 22.10.2
  "@types/react": 18.3.16
  "@types/react-dom": 18.3.5
  "@vercel/functions": 1.5.1
  hono: 4.6.13
  next: 15.1.2
  next-axiom: 1.8.0
  pino: 9.5.0
  postcss: ^8.4.49
  react: 18.3.1
  react-dom: 18.3.1
  server-only: 0.0.1
  tailwindcss: ^3.4.16
  typescript: 5.7.2
  vitest: ^2.1.8
  zod: 3.24.1
