name: init

services:
  redis:
    image: redis:7.4.0
    ports:
      - "6379:6379"
    volumes:
      - ./.data/redis-data:/data

  serverless-redis-http:
    ports:
      - "8079:80"
    image: hiett/serverless-redis-http:0.0.10
    environment:
      SRH_MODE: env
      SRH_TOKEN: "my-redis-rest-token"
      SRH_CONNECTION_STRING: "redis://redis:6379"
    depends_on:
      - redis

  postgres:
    image: postgres:17
    command: "-d 1"
    volumes:
      - ./.data/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  neon-proxy:
    image: ghcr.io/timowilhelm/local-neon-http-proxy:main
    environment:
      - PG_CONNECTION_STRING=postgres://postgres:postgres@postgres:5432/main
    ports:
      - "4444:4444"
    depends_on:
      postgres:
        condition: service_healthy
